apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: test-ns
data:
  nginx.conf: |
    events { worker_connections 1024; }

    http {
        include /etc/nginx/mime.types;
        sendfile on;

        upstream frontend {
           # server 10.96.100.219:5173;
           server 10.96.205.220:4001;
        }

        upstream backend {
            server 10.96.205.220:4001;
        }

        server {
            listen 80;

            location / {
                proxy_pass http://10.96.100.219:5173/api/;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }

            location /api/ {
                proxy_pass http://10.96.205.220:4001/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }

